---
- name: Install Applications
  hosts: osx

  vars:
    gui_apps:
      - ableton-live-suite
      - balenaetcher
      - cyberduck
      - firefox
      - google-chrome
      - iterm2
      - little-snitch
      - microsoft-office
      - musescore
      - raspberry-pi-imager
      - tunnelblick
      - visual-studio-code
      - vlc
      - wireshark
    cli_apps:
      - dockutil
      - iperf3
    drivers:
      - logi-options-plus

  tasks:
    - name: Ensure Homebrew is up-to-date
      homebrew:
        update_homebrew: yes

    - name: Install Homebrew(CLI) Applications
      homebrew:
        name: "{{ cli_apps }}"
        state: present

    - name: Install Homebrew Cask(GUI) Applications
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items: "{{ gui_apps }}"

    - name: Install Homebrew Drivers Repository
      community.general.homebrew_tap:
        name: homebrew/cask-drivers

    - name: Install Homebrew Driver Applications
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items: "{{ drivers }}"
