---
- name: Configure the Dock
  hosts: osx

  tasks:
    - name: Disable - Show recent applications in Dock
      ansible.builtin.command: defaults write com.apple.dock show-recents -bool false

    - name: Clear the dock
      ansible.builtin.shell: dockutil --remove all

    - name: Add Launchpad
      ansible.builtin.shell: dockutil --add /System/Applications/Launchpad.app

    - name: Add Apple Music
      ansible.builtin.command: dockutil --add /System/Applications/Music.app

    - name: Add Messages
      ansible.builtin.command: dockutil --add /System/Applications/Messages.app

    - name: Add Firefox
      ansible.builtin.command: dockutil --add /Applications/Firefox.app

    - name: Add Visual Studio Code
      ansible.builtin.command: dockutil --add /Applications/Visual\ Studio\ Code.app

    - name: Add iTerm
      ansible.builtin.command: dockutil --add /Applications/iTerm.app

    - name: Add Cyberduck
      ansible.builtin.command: dockutil --add /Applications/Cyberduck.app
